# Generated by Django 5.2.7 on 2025-10-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('contenido_teoria', models.TextField(null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='bloques/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('filas_circuito', models.IntegerField(default=2)),
                ('columnas_circuito', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'contenidos_bloque',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CircuitoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('nodes', models.JSONField()),
                ('edges', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_renderizada', models.ImageField(blank=True, null=True, upload_to='circuitos_generados/')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos_generados', to='contenidos.bloque')),
            ],
            options={
                'verbose_name': 'Circuito Generado',
                'verbose_name_plural': 'Circuitos Generados',
                'db_table': 'contenidos_circuito_generado',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('numerica', 'Numérica'), ('texto', 'Texto')], max_length=20)),
                ('opciones', models.JSONField(blank=True, help_text='Array de opciones', null=True)),
                ('respuesta_correcta', models.TextField()),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('puntos', models.IntegerField(default=1)),
                ('componente_relacionado', models.CharField(blank=True, help_text='Ej: N11-N12 (resistor)', max_length=50, null=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='contenidos.circuitogenerado')),
            ],
            options={
                'verbose_name': 'Pregunta Generada',
                'verbose_name_plural': 'Preguntas Generadas',
                'db_table': 'contenidos_preguntagenerada',
                'ordering': ['circuito', 'orden'],
                'unique_together': {('circuito', 'orden')},
            },
        ),
    ]
