# Generated by Django 5.2.7 on 2025-10-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_dada', models.TextField(max_length=255)),
                ('correcta', models.BooleanField()),
                ('tiempo_respuesta_segundos', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuarios',
                'db_table': 'ejercicios_respuestausuario',
                'ordering': ['intento', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'ejercicios_sesion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_segundos', models.IntegerField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('puntuacion_obtenida', models.IntegerField(default=0)),
                ('puntuacion_maxima', models.IntegerField(default=0)),
                ('porcentaje_acierto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='contenidos.bloque')),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='contenidos.circuitogenerado')),
            ],
            options={
                'verbose_name': 'Intento',
                'verbose_name_plural': 'Intentos',
                'db_table': 'ejercicios_intento',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
